routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ListingController@home');


Route::prefix('admin')->group(function() {
    Auth::routes();
});

Route::middleware('auth')->group(function(){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('kategori', 'KategoriController');
    Route::resource('user', 'UserController');
    Route::resource('artikel', 'ArtikelController');
    Route::get('ubah-password', 'ChangePasswordController@index');
    Route::post('ubah-password', 'ChangePasswordController@update')->name('password.update');
    Route::resource('mahasiswa', 'MahasiswaController');

    Route::middleware('konselor')->group(function(){
        Route::get('konseling', 'KonselingController@index');
        Route::get('konseling/response/{id}', 'KonselingController@response')->name('konseling.show');
        Route::get('konseling/response/{konseling_id}/form', 'ResponController@create')->name('konseling.respon_form');
        Route::post('konseling/response/store', 'ResponController@store')->name('respon.store');
    });
});

Route::get('login', 'MahasiswaLoginController@showLoginForm')->name('mahasiswa.loginform');
Route::get('register', 'MahasiswaRegisterController@showRegisterForm')->name('mahasiswa.registerform');
Route::post('login', 'MahasiswaLoginController@login')->name('mahasiswa.login');
Route::post('register', 'MahasiswaRegisterController@register')->name('mahasiswa.register');
Route::post('logout', 'MahasiswaLoginController@logout')->name('mahasiswa.logout');

Route::get('read/{id}', 'ListingController@read')->name('artikel.read');

Route::get('konseling/detail/{konseling_id}', 'KonselingController@response')->name('konseling.detail');

Route::get('listing/konseling/', 'ListingController@konseling');
Route::get('listing/konseling/{kategori_id}', 'ListingController@konseling');

Route::get('listing/artikel/', 'ListingController@artikel');
Route::get('listing/artikel/{kategori_id}', 'ListingController@artikel');

Route::middleware('auth.mahasiswa:mahasiswa')->group(function(){
    Route::resource('komentar', 'KomentarController');
    Route::get('profile', 'ListingController@profile');
    Route::get('ganti-password', 'ChangePasswordController@index');
    Route::post('ganti-password', 'ChangePasswordController@update')->name('password.update.mahasiswa');
    Route::get('konseling/form', 'KonselingController@create')->name('konseling.create');
    Route::post('konseling/form', 'KonselingController@store')->name('konseling.store');
    Route::get('konseling/{konseling_id}/form-respon', 'ResponController@create')->name('konseling.respon_form_mahasiswa');
    Route::post('konseling/form-respon', 'ResponController@store')->name('respon.store_respon_mahasiswa');
    Route::get('daftar-konseling', 'ListingController@konselingSaya');
});

app/Artikel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Artikel extends Model
{
    protected $table = 'artikel';

    protected $fillable = [
        'waktu',
        'judul',
        'isi',
        'cover',
        'kategori_id',
        'user_id',
    ];

    public function kategori()
    {
        return $this->belongsTo('App\Kategori');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function comments()
    {
        return $this->hasMany('App\Komentar');
    }

    public function getDefaultValues()
    {
        return [
            'waktu' => '',
            'judul' => '',
            'isi' => '',
            'cover' => '',
            'kategori_id' => '',
            'user_id' => '',
        ];
    }
}

app/Http/Controllers/ArtikelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Artikel;
use App\Http\Requests\StoreArtikel;
use App\Kategori;
use Auth;

class ArtikelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $artikel;

    public function __construct()
    {
        $this->artikel = new Artikel();
    }

    public function index()
    {
        return view('admin.artikel.index', ['artikel' => $this->artikel->all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('admin.artikel.form', ['artikel' => (object) $this->artikel->getDefaultValues(), 'kategori' => Kategori::orderBy('nama_kategori')->get() ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreArtikel $request)
    {
        $input = $request->all();
        $input['cover'] = '';
        if($request->hasFile('cover')){
            $upload = $request->cover->store('cover');
            $input['cover'] = $request->cover->hashName();
        }

        $input['user_id'] = Auth::user()->id;
        $input['waktu'] = $request['waktu']. ' ' . date('H:i:s');
        $insert = $this->artikel->create($input);
        if($insert){
            return redirect('artikel')->with('success', 'Berhasil menambah data artikel');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view ('admin.artikel.form', ['artikel' => $this->artikel->find($id), 'kategori' => Kategori::orderBy('nama_kategori')->get() ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view ('admin.artikel.form', ['artikel' => $this->artikel->find($id), 'kategori' => Kategori::orderBy('nama_kategori')->get() ]);    
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $artikel = $this->artikel->find($id);

        if($request->hasFile('cover')){
            //remove old photos
            if(is_file('storage/cover/'.$artikel->cover)){
                unlink('storage/cover/'.$artikel->cover);
            }
            $request->cover->store('cover');
        } else {
            $rename = $artikel->cover;
        }

        $input = $request->all();

        if($input['waktu'] != $artikel->waktu){
            $input['waktu'] = $input['waktu'] . ' ' . date('H:i:s');
        }
        $input['cover'] = $request->cover->hashName();

        $artikel->update($input);

        return redirect('artikel')->with('success', 'Berhasil menambah mengubah artikel');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $artikel = $this->artikel->find($id);
        if($artikel->cover != ''){
            //remove old photos
            if(is_file('storage/cover/'.$artikel->cover)){
                unlink('storage/cover/'.$artikel->cover);
            }
        }
        $artikel->delete();
        return redirect('artikel')->with('success', 'Berhasil menambah menghapus artikel');
    }
}

resources/views/admin/artikel/form.blade.php
@extends('admin.layouts.app')

@section('title', 'Form Artikel')

@section('content')
<div class="row">
    <div class="col-md-12">                        
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Form Artikel</h4>
                <hr>
                <form action="{{ (!isset($artikel->id)) ? route('artikel.store') : route('artikel.update', $artikel->id) }}" method="post" enctype="multipart/form-data">        
                    @csrf
                    @isset($artikel->id)
                        {{ method_field('PUT')}}
                    @endisset
                    <div class="form-group">
                        <label>Judul Artikel</label>
                        <input type="text" name="judul" class="form-control" value="{{ old('judul', $artikel->judul) }}" placeholder="Judul artikel">
                        @error('judul')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="form-group">       
                        <label>Kategori Artikel</label>
                        <select name="kategori_id" class="mySelect custom-select">
                            <option value=""> - Pilih Kategori Artikel - </option>
                                @foreach($kategori as $option)
                                    <option value="{{ $option->id }}" {{ (old('kategori_id') == $option->id || $artikel->kategori_id == $option->id) ? 'selected' : '' }}> {{ $option->nama_kategori }} </option>                            
                                @endforeach
                            </select>
                            @error('kategori_id')
                                <p class="text-danger">{{ $message }}</p>
                            @enderror
                    </div>
                    <div class="form-group">
                        <label>Tanggal</label>
                        <input type="text" name="waktu" class="form-control datepicker2" value="{{ old('waktu', $artikel->waktu) }}" placeholder="Masukan Tanggal">
                        @error('tanggal')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    
                    <div class="form-group">
                        <label>Isi</label>
                        <textarea name="isi" class="form-control" id="myeditor">{{ old('isi', $artikel->isi) }}</textarea>
                        @error('isi')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    
                    @isset($artikel->id)
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                Cover
                                <hr>
                                <?php if($artikel->cover != null | $artikel->cover != ''): ?>
                                    <!-- HAVE PHOTO -->
                                    <img src="{{ asset('storage/cover/'.$artikel->cover) }}" alt="image-cover" class="img-fluid">
                                <?php else : ?>
                                    <!-- NOT HAVE PHOTO -->
                                    <img src="{{ asset('storage/cover/tidak-ada-foto.jpg') }}" alt="no-cover" class="img-fluid">
                                <?php endif ?>
                            </div>
                        </div>
                    </div>
                    @endisset
                    <div class="form-group">
                        <label>Cover</label>
                        <input type="file" name="cover" class="form-control">
                        @error('cover')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="form-group">
                        <input type="submit" class="btn btn-success float-right" value="Simpan">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
<script>

     // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace( 'myeditor' );

</script>
@endpush

resources/views/admin/artikel/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Artikel')

@section('content')
<div class="row">
    <div class="col-md-12">                        
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Data Artikel</h4>
                <hr>
                <a href="{{ route('artikel.create') }}" class="btn btn-sm btn-primary mb-3"><i class="fa fa-plus"></i> Tambah </a>
                <div class="data-tables inner-content">
                    <table id="dataTable" class="text-center table">
                        <thead class="bg-light text-capitalize">
                            <tr>
                                <th>No</th>
                                <th width="160">Judul</th>
                                <th width="78">Tanggal</th>
                                <th>Isi</th>
                                <th>Cover</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($artikel as $row)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $row->judul }}</td>
                                    <td>{{ $row->waktu }} <div class="mt-2"></div> <span class="badge badge-info">{{ $row->kategori->nama_kategori }}</span> </td>
                                    <td>
                                        @if(strlen($row->isi) > 240)
                                            {!! strip_tags(substr($row->isi, 0, 240)) !!} <a href="{{ route('artikel.show', $row->id) }}">Read More...</a>
                                        @else
                                            {!! strip_tags($row->isi) !!}
                                        @endif
                                    </td>
                                    <td class="image-td">
                                        <?php if($row->cover != null | $row->cover != ''): ?>
                                            <!-- HAVE PHOTO -->
                                            <img src="{{ asset('storage/cover/'.$row->cover) }}" alt="image-cover">
                                        <?php else : ?>
                                            <!-- NOT HAVE PHOTO -->
                                            <img src="{{ asset('storage/cover/tidak-ada-foto.jpg') }}" alt="no-cover">
                                        <?php endif ?>
                                     </td>
                
                                    <td>
                                        <form action="{{ route('artikel.destroy', $row->id) }}" method="post">
                                            @csrf 
                                            @method('DELETE')
                                            <ul class="d-flex justify-content-center"> 
                                                <li class="mr-3"><a href="{{ route('artikel.read', $row->id) }}" target="_blank" class="text-primary detail-btn" title="Lihat detail"><i class="fa fa-eye"></i></a> </li>
                                                <li class="mr-3"><a href="{{ route('artikel.edit', $row->id) }}" class="text-secondary" title="Edit data"><i class="fa fa-edit"></i></a></li>
                                                <li><button type="submit" class="text-danger btn-submit" onclick="return confirm('Yakin akan hapus data?')" ><i class="fa fa-trash"></i></button></li>
                                            </ul>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection