routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ListingController@home');


Route::prefix('admin')->group(function() {
    Auth::routes();
});

Route::middleware('auth')->group(function(){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('kategori', 'KategoriController');
    Route::resource('user', 'UserController');
    Route::resource('artikel', 'ArtikelController');
    Route::get('ubah-password', 'ChangePasswordController@index');
    Route::post('ubah-password', 'ChangePasswordController@update')->name('password.update');
    Route::resource('mahasiswa', 'MahasiswaController');

    Route::middleware('konselor')->group(function(){
        Route::get('konseling', 'KonselingController@index');
        Route::get('konseling/response/{id}', 'KonselingController@response')->name('konseling.show');
        Route::get('konseling/response/{konseling_id}/form', 'ResponController@create')->name('konseling.respon_form');
        Route::post('konseling/response/store', 'ResponController@store')->name('respon.store');
    });
});

Route::get('login', 'MahasiswaLoginController@showLoginForm')->name('mahasiswa.loginform');
Route::get('register', 'MahasiswaRegisterController@showRegisterForm')->name('mahasiswa.registerform');
Route::post('login', 'MahasiswaLoginController@login')->name('mahasiswa.login');
Route::post('register', 'MahasiswaRegisterController@register')->name('mahasiswa.register');
Route::post('logout', 'MahasiswaLoginController@logout')->name('mahasiswa.logout');

Route::get('read/{id}', 'ListingController@read')->name('artikel.read');

Route::get('konseling/detail/{konseling_id}', 'KonselingController@response')->name('konseling.detail');

Route::get('listing/konseling/', 'ListingController@konseling');
Route::get('listing/konseling/{kategori_id}', 'ListingController@konseling');

Route::get('listing/artikel/', 'ListingController@artikel');
Route::get('listing/artikel/{kategori_id}', 'ListingController@artikel');

Route::middleware('auth.mahasiswa:mahasiswa')->group(function(){
    Route::resource('komentar', 'KomentarController');
    Route::get('profile', 'ListingController@profile');
    Route::get('ganti-password', 'ChangePasswordController@index');
    Route::post('ganti-password', 'ChangePasswordController@update')->name('password.update.mahasiswa');
    Route::get('konseling/form', 'KonselingController@create')->name('konseling.create');
    Route::post('konseling/form', 'KonselingController@store')->name('konseling.store');
    Route::get('konseling/{konseling_id}/form-respon', 'ResponController@create')->name('konseling.respon_form_mahasiswa');
    Route::post('konseling/form-respon', 'ResponController@store')->name('respon.store_respon_mahasiswa');
    Route::get('daftar-konseling', 'ListingController@konselingSaya');
});

app/Kategori.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    protected $table = 'kategori';

    protected $fillable = [
        'nama_kategori',
        'keterangan'
    ];

    public function konseling()
    {
        return $this->hasMany('App\Konseling');
    }

    public function artikel()
    {
        return $this->hasMany('App\Artikel');
    }

    public function getDefaultValues()
    {
        return [
            'nama_kategori' => '',
            'keterangan' => ''
        ];
    }
}

app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Kategori;


class KategoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $kategori;

    public function __construct()
    {
        $this->kategori = new Kategori();
    }

    public function index()
    {
        return view('admin.kategori.index', ['categories' => Kategori::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['kategori'] = (object) $this->kategori->getDefaultValues();
        return view('admin.kategori.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_kategori' => 'required'
        ]);

        $this->kategori->create($request->all());
        return redirect('kategori')->with('success', 'Berhasil menambah data kategori');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['kategori'] = $this->kategori->findOrFail($id);
        return view('admin.kategori.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama_kategori' => 'required'
        ]);

        $this->kategori->findOrFail($id)->update($request->all());
        return redirect('kategori')->with('success', 'Berhasil mengubah data kategori');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->kategori->findOrFail($id)->delete();
        return redirect('kategori')->with('success', 'Berhasil menghapus data kategori');
    }
}

resources/views/admin/kategori/form.blade.php
@extends('admin.layouts.app')

@section('title', 'Form Kategori')

@section('content')
<div class="row">
    <div class="col-md-8">                        
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Form Kategori</h4>
                <hr>
                <form action="{{ (!isset($kategori->id)) ? route('kategori.store') : route('kategori.update', $kategori->id) }}" method="post">
                    @csrf
                    @isset($kategori->id)
                        {{ method_field('PUT')}}
                    @endisset
                    <div class="form-group">       
                        <label>Nama Kategori</label>
                        <input type="text" placeholder="Masukan Nama Kategori" class="form-control" name="nama_kategori" value="{{ old('nama_kategori', $kategori->nama_kategori) }}">
                        @error('nama_kategori')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="form-group">       
                        <label>Keterangan</label>
                        <textarea name="keterangan" class="form-control" placeholder="Masukan Keterangan (opsional)">{{ old('keterangan', $kategori->keterangan) }}</textarea>
                    </div>    
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div>                  
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/kategori/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Kategori')

@section('content')
<div class="row">
    <div class="col-md-12">                        
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Data Kategori</h4>
                <hr>
                <a href="{{ route('kategori.create') }}" class="btn btn-sm btn-primary mb-3"><i class="fa fa-plus"></i> Tambah </a>
                <div class="data-tables inner-content">
                    <table id="dataTable" class="text-center table">
                        <thead class="bg-light text-capitalize">
                            <tr>
                                <th>No</th>
                                <th>Nama Kategori</th>
                                <th>Keterangan</th>                            
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($categories as $row)
                                <tr>
                                    <td><?= $loop->iteration ?></td>
                                    <td><?=  $row->nama_kategori ?></td>
                                    <td><?=  $row->keterangan ?></td>                                    
                                    <td>
                                        <form action="{{ route('kategori.destroy', $row->id) }}" method="post">
                                            @csrf 
                                            @method('delete')
                                            <ul class="d-flex justify-content-center">
                                                <li class="mr-3"><a href="{{ route('kategori.edit', $row->id) }}" class="text-secondary" title="Edit data"><i class="fa fa-edit"></i></a></li>
                                                <li><button type="submit" class="text-danger btn-submit" onclick="return confirm('Yakin akan hapus data?')" ><i class="fa fa-trash"></i></button></li>
                                            </ul>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection