routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ListingController@home');


Route::prefix('admin')->group(function() {
    Auth::routes();
});

Route::middleware('auth')->group(function(){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('kategori', 'KategoriController');
    Route::resource('user', 'UserController');
    Route::resource('artikel', 'ArtikelController');
    Route::get('ubah-password', 'ChangePasswordController@index');
    Route::post('ubah-password', 'ChangePasswordController@update')->name('password.update');
    Route::resource('mahasiswa', 'MahasiswaController');

    Route::middleware('konselor')->group(function(){
        Route::get('konseling', 'KonselingController@index');
        Route::get('konseling/response/{id}', 'KonselingController@response')->name('konseling.show');
        Route::get('konseling/response/{konseling_id}/form', 'ResponController@create')->name('konseling.respon_form');
        Route::post('konseling/response/store', 'ResponController@store')->name('respon.store');
    });
});

Route::get('login', 'MahasiswaLoginController@showLoginForm')->name('mahasiswa.loginform');
Route::get('register', 'MahasiswaRegisterController@showRegisterForm')->name('mahasiswa.registerform');
Route::post('login', 'MahasiswaLoginController@login')->name('mahasiswa.login');
Route::post('register', 'MahasiswaRegisterController@register')->name('mahasiswa.register');
Route::post('logout', 'MahasiswaLoginController@logout')->name('mahasiswa.logout');

Route::get('read/{id}', 'ListingController@read')->name('artikel.read');

Route::get('konseling/detail/{konseling_id}', 'KonselingController@response')->name('konseling.detail');

Route::get('listing/konseling/', 'ListingController@konseling');
Route::get('listing/konseling/{kategori_id}', 'ListingController@konseling');

Route::get('listing/artikel/', 'ListingController@artikel');
Route::get('listing/artikel/{kategori_id}', 'ListingController@artikel');

Route::middleware('auth.mahasiswa:mahasiswa')->group(function(){
    Route::resource('komentar', 'KomentarController');
    Route::get('profile', 'ListingController@profile');
    Route::get('ganti-password', 'ChangePasswordController@index');
    Route::post('ganti-password', 'ChangePasswordController@update')->name('password.update.mahasiswa');
    Route::get('konseling/form', 'KonselingController@create')->name('konseling.create');
    Route::post('konseling/form', 'KonselingController@store')->name('konseling.store');
    Route::get('konseling/{konseling_id}/form-respon', 'ResponController@create')->name('konseling.respon_form_mahasiswa');
    Route::post('konseling/form-respon', 'ResponController@store')->name('respon.store_respon_mahasiswa');
    Route::get('daftar-konseling', 'ListingController@konselingSaya');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nama', 'username', 'password', 'role', 'jenis_kelamin', 'tanggal_lahir', 'alamat', 'no_telp', 'status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPasswordAttribute($val)
    {
        return $this->attributes['password'] = bcrypt($val);
    }

    public function getDefaultValues()
    {
        return [
            'nama' => '', 
            'username' => '', 
            'password' => '', 
            'role' => '', 
            'jenis_kelamin' => '', 
            'tanggal_lahir' => '', 
            'alamat' => '', 
            'no_telp' => '', 
            'status' => ''
        ];  
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Http\Requests\StoreUser;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $user;

    public function __construct()
    {
        $this->user = new User();
    }

    public function index()
    {
        return view('admin.user.index', ['users' => $this->user->all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['user'] = (object) $this->user->getDefaultValues();
        return view('admin.user.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUser $request)
    {
        $this->user->create($request->all());
        return redirect('user')->with('success', 'Berhasil menambah data user');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('admin.user.modal', ['user' => $this->user->findOrFail($id)]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.user.form', ['user' => $this->user->findOrFail($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreUser $request, $id)
    {
        $this->user->findOrFail($id)->update($request->all());
        return redirect('user')->with('success', 'Berhasil mengubah data user');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->user->findOrFail($id)->delete();
        return redirect('user')->with('success', 'Berhasil menghapus data user');
    }
}

resources/views/admin/user/form.blade.php
@extends('admin.layouts.app')

@section('title', 'Form user')

@section('content')
<div class="row">
    <div class="col-md-12">                        
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Form User</h4>
                <hr>
                <form action="{{ (!isset($user->id)) ? route('user.store') : route('user.update', $user->id) }}" method="post">
                    @csrf
                    @isset($user->id)
                        {{ method_field('PUT')}}
                    @endisset
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">       
                                <label>Nama user</label>
                                <input type="text" placeholder="Masukan Nama user" class="form-control" name="nama" value="{{ old('nama', $user->nama) }}">
                                @error('nama')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">       
                                <label>No. Telp</label>
                                <input type="number" placeholder="Masukan Nomor Telepon" class="form-control" name="no_telp" value="{{ old('no_telp', $user->no_telp) }}">
                                @error('no_telp')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">       
                                <label>Tanggal Lahir</label>
                                <input type="text" placeholder="Masukan Tanggal Lahir" class="form-control datepicker" name="tanggal_lahir" value="{{ old('tanggal_lahir', $user->tanggal_lahir) }}">
                                @error('tanggal_lahir')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">       
                                <label>Jenis Kelamin</label>
                                <select name="jenis_kelamin" class="mySelect custom-select">
                                    <option value=""> - Pilih Jenis Kelamin - </option>
                                    <option value="l" {{ (old('jenis_kelamin') == 'l' || $user->jenis_kelamin == 'l') ? 'selected' : '' }}> Laki - Laki</option>
                                    <option value="p" {{ (old('jenis_kelamin') == 'p' || $user->jenis_kelamin == 'p') ? 'selected' : '' }}> Perempuan</option>
                                </select>
                                @error('jenis_kelamin')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <div class="form-group">       
                        <label>alamat</label>
                        <textarea name="alamat" class="form-control" placeholder="Masukan alamat">{{ old('alamat', $user->alamat) }}</textarea>
                        @error('alamat')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                
                    <div class="form-group">       
                        <label>Username</label>
                        <input type="text" placeholder="Masukan Username" class="form-control" name="username" value="{{ old('username', $user->username) }}">
                        @error('username')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror                  
                    </div>
                    @if(!isset($user->id))
                    <div class="form-group">       
                        <label>Password</label>
                        <input type="password" placeholder="Masukan Pasword" class="form-control" name="password" value="{{ old('password', $user->password) }}">
                        @error('password')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror                        
                    </div>
                    @endif
                  
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">       
                                <label>Role</label>
                                <select name="role" class="mySelect custom-select">
                                    <option value=""> - Pilih Role - </option>
                                    <option value="admin" {{ (old('role') == 'l' || $user->role == 'admin') ? 'selected' : '' }}> Admin</option>
                                    <option value="konselor" {{ (old('role') == 'p' || $user->role == 'konselor') ? 'selected' : '' }}> Konselor</option>
                                </select>
                                @error('role')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">       
                                <label>Status</label>
                                <select name="status" class="mySelect custom-select">
                                    <option value=""> - Pilih Status - </option>
                                    <option value="1" {{ (old('status') == '1' || $user->status == '1') ? 'selected' : '' }}> Aktif</option>
                                    <option value="0" {{ (old('status') == '0' || $user->status == '0') ? 'selected' : '' }}> Tidak Aktif</option>
                                </select>
                                @error('status')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div>                  
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.app')

@section('title', 'User')

@section('content')
<div class="row">
    <div class="col-md-12">                        
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Data User</h4>
                <hr>
                <a href="{{ route('user.create') }}" class="btn btn-sm btn-primary mb-3"><i class="fa fa-plus"></i> Tambah </a>
                <div class="data-tables inner-content">
                    <table id="dataTable" class="text-center table">
                        <thead class="bg-light text-capitalize">
                            <tr>
                                <th>No</th>
                                <th>Nama</th>
                                <th>Username</th>
                                <th>Role</th>
                                <th>Status</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($users as $row)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{  $row->nama }}</td>
                                    <td>{{  $row->username }}</td>
                                    <td>{{  $row->role }}</td>
                                    <td>
                                        <span class="badge {{ ($row->status == '1') ? 'badge-success' : 'badge-danger' }}">{{ ($row->status == '1') ? 'Aktif' : 'Tidak Aktif' }}</span>
                                    </td>
                                    <td>
                                        <form action="{{ route('user.destroy', $row->id) }}" method="post">
                                            @csrf 
                                            @method('delete')
                                            <ul class="d-flex justify-content-center">
                                                <li class="mr-3"><a href="{{ route('user.show', $row->id) }}" class="text-primary modal-btn" title="Lihat detail"><i class="fa fa-eye"></i></a> </li>
                                                <li class="mr-3"><a href="{{ route('user.edit', $row->id) }}" class="text-secondary" title="Edit data"><i class="fa fa-edit"></i></a></li>
                                                <li><button type="submit" class="text-danger btn-submit" onclick="return confirm('Yakin akan hapus data?')" ><i class="fa fa-trash"></i></button></li>
                                            </ul>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')

<div id="theModal" class="modal fade text-center">
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>

<script>
    $('.modal-btn').on('click', function(e){
        e.preventDefault();
        $('#theModal').modal('show').find('.modal-content').load($(this).attr('href'));
    });
</script>
@endpush

resources/views/admin/user/modal.blade.php
<div class="modal-header">
    <h5 class="modal-title">Detail User</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <div class="text-left">
        <h5 class="mb-3">
            {{ ucwords($user->nama) }}
        </h5>

        <table class="table">
            <tr>
                <td>Tanggal Lahir</td>
                <td>:</td>
                <td>{{ $user->tanggal_lahir }}</td>
            </tr>
            <tr>
                <td>Jenis Kelamin</td>
                <td>:</td>
                <td>{{ ($user->jenis_kelamin == 'l') ? 'Laki - Laki' : 'Perempuan' }}</td>
            </tr>
            <tr>
                <td>No. Telp</td>
                <td>:</td>
                <td>{{ $user->no_telp }}</td>
            </tr>
            <tr>
                <td>Alamat</td>
                <td>:</td>
                <td>{{ $user->alamat }}</td>
            </tr>
            <tr>
                <td>Role</td>
                <td>:</td>
                <td>{{ $user->role }}</td>
            </tr>
            <tr>
                <td>Username</td>
                <td>:</td>
                <td>{{ $user->username }}</td>
            </tr>
            <tr>
                <td>Status</td>
                <td>:</td>
                <td><span class="badge {{ ($user->status == '1') ? 'badge-success' : 'badge-danger' }}">{{ ($user->status == '1') ? 'Aktif' : 'Tidak Aktif' }}</span></td>
            </tr>
        </table>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>