routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ListingController@home');


Route::prefix('admin')->group(function() {
    Auth::routes();
});

Route::middleware('auth')->group(function(){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('kategori', 'KategoriController');
    Route::resource('user', 'UserController');
    Route::resource('artikel', 'ArtikelController');
    Route::get('ubah-password', 'ChangePasswordController@index');
    Route::post('ubah-password', 'ChangePasswordController@update')->name('password.update');
    Route::resource('mahasiswa', 'MahasiswaController');

    Route::middleware('konselor')->group(function(){
        Route::get('konseling', 'KonselingController@index');
        Route::get('konseling/response/{id}', 'KonselingController@response')->name('konseling.show');
        Route::get('konseling/response/{konseling_id}/form', 'ResponController@create')->name('konseling.respon_form');
        Route::post('konseling/response/store', 'ResponController@store')->name('respon.store');
    });
});

Route::get('login', 'MahasiswaLoginController@showLoginForm')->name('mahasiswa.loginform');
Route::get('register', 'MahasiswaRegisterController@showRegisterForm')->name('mahasiswa.registerform');
Route::post('login', 'MahasiswaLoginController@login')->name('mahasiswa.login');
Route::post('register', 'MahasiswaRegisterController@register')->name('mahasiswa.register');
Route::post('logout', 'MahasiswaLoginController@logout')->name('mahasiswa.logout');

Route::get('read/{id}', 'ListingController@read')->name('artikel.read');

Route::get('konseling/detail/{konseling_id}', 'KonselingController@response')->name('konseling.detail');

Route::get('listing/konseling/', 'ListingController@konseling');
Route::get('listing/konseling/{kategori_id}', 'ListingController@konseling');

Route::get('listing/artikel/', 'ListingController@artikel');
Route::get('listing/artikel/{kategori_id}', 'ListingController@artikel');

Route::middleware('auth.mahasiswa:mahasiswa')->group(function(){
    Route::resource('komentar', 'KomentarController');
    Route::get('profile', 'ListingController@profile');
    Route::get('ganti-password', 'ChangePasswordController@index');
    Route::post('ganti-password', 'ChangePasswordController@update')->name('password.update.mahasiswa');
    Route::get('konseling/form', 'KonselingController@create')->name('konseling.create');
    Route::post('konseling/form', 'KonselingController@store')->name('konseling.store');
    Route::get('konseling/{konseling_id}/form-respon', 'ResponController@create')->name('konseling.respon_form_mahasiswa');
    Route::post('konseling/form-respon', 'ResponController@store')->name('respon.store_respon_mahasiswa');
    Route::get('daftar-konseling', 'ListingController@konselingSaya');
});

app/Mahasiswa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;


class Mahasiswa extends Authenticatable
{
    protected $table = 'mahasiswa';

    protected $fillable = [
        'nrm',
        'nama',
        'fakultas',
        'prodi',
        'angkatan',
        'jenis_kelamin',
        'tanggal_lahir',
        'alamat',
        'no_telp',
        'password'
    ];

    protected $hidden = ['password'];

    public function setPasswordAttribute($val)
    {
        return $this->attributes['password'] = bcrypt($val);
    }

    public function konseling()
    {
        return $this->hasMany('App\Konseling');
    }
}

app/Http/Controllers/MahasiswaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreMahasiswa;
use App\Mahasiswa;
use Illuminate\Http\Request;

class MahasiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $mahasiswa;
    
    public function __construct()
    {
        $this->mahasiswa = new Mahasiswa();
    }

    public function index()
    {
        return view('admin.mahasiswa.index', ['mahasiswa' => $this->mahasiswa->orderBy('nrm', 'asc')->get()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('admin.mahasiswa.modal', ['mahasiswa' => $this->mahasiswa->findOrFail($id)]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.mahasiswa.form', ['mahasiswa' => $this->mahasiswa->findOrFail($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreMahasiswa $request, $id)
    {
        $this->mahasiswa->find($id)->update($request->all());
        return redirect()->route('mahasiswa.index')->with('success', 'Berhasil mengubah data mahasiswa');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->mahasiswa->find($id)->delete();
        return redirect()->route('mahasiswa.index')->with('success', 'Berhasil menghapus data mahasiswa');
    }
}

resources/views/admin/mahasiswa/form.blade.php
@extends('admin.layouts.app')

@section('title', 'Form Mahasiswa')

@section('content')
<div class="row">
    <div class="col-md-12">                        
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Form Mahasiswa</h4>
                <hr>
                <form action="{{ (!isset($mahasiswa->id)) ? route('mahasiswa.store') : route('mahasiswa.update', $mahasiswa->id) }}" method="post">
                    @csrf
                    @isset($mahasiswa->id)
                        {{ method_field('PUT')}}
                    @endisset
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">       
                                <label>Nama Mahasiswa</label>
                                <input type="text" placeholder="Masukan nama mahasiswa" class="form-control" name="nama" value="{{ old('nama', $mahasiswa->nama) }}">
                                @error('nama')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">       
                                <label>NRM</label>
                                <input type="text" placeholder="Masukan NRM mahasiswa" class="form-control" name="nrm" value="{{ old('nrm', $mahasiswa->nrm) }}">
                                @error('nrm')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">       
                                <label>Fakultas</label>
                                <input type="text" placeholder="Masukan fakultas" class="form-control" name="fakultas" value="{{ old('fakultas', $mahasiswa->fakultas) }}">
                                @error('fakultas')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">       
                                <label>Prodi</label>
                                <input type="text" placeholder="Masukan prodi mahasiswa" class="form-control" name="prodi" value="{{ old('prodi', $mahasiswa->prodi) }}">
                                @error('prodi')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">       
                                <label>Angkatan</label>
                                <input type="text" placeholder="Masukan angkatan" class="form-control" name="angkatan" value="{{ old('angkatan', $mahasiswa->angkatan) }}">
                                @error('angkatan')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">       
                                <label>no_telp</label>
                                <input type="number" placeholder="Masukan no_telp mahasiswa" class="form-control" name="no_telp" value="{{ old('no_telp', $mahasiswa->no_telp) }}">
                                @error('no_telp')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">       
                                <label>Tanggal Lahir</label>
                                <input type="text" placeholder="Masukan tanggal lahir" class="form-control" name="tanggal_lahir" value="{{ old('tanggal_lahir', $mahasiswa->tanggal_lahir) }}">
                                @error('tanggal_lahir')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">       
                                <label>Jenis kelamin</label>
                                <select name="jenis_kelamin" class="mySelect custom-select">
                                    <option value=""> - Pilih Jenis Kelamin - </option>
                                    <option value="l" {{ (old('jenis_kelamin') == 'l' || $mahasiswa->jenis_kelamin == 'l') ? 'selected' : '' }}> Laki - Laki</option>
                                    <option value="p" {{ (old('jenis_kelamin') == 'p' || $mahasiswa->jenis_kelamin == 'p') ? 'selected' : '' }}> Perempuan</option>
                                </select>
                                @error('jenis_kelamin')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <div class="form-group">       
                        <label>Alamat</label>
                        <textarea name="alamat" class="form-control" placeholder="Masukan alamat">{{ old('alamat', $mahasiswa->alamat) }}</textarea>
                    </div>
                    @error('alamat')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div>                  
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/mahasiswa/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Mahasiswa')

@section('content')
<div class="row">
    <div class="col-md-12">                        
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Data mahasiswa</h4>
                <hr>
                <div class="data-tables inner-content">
                    <table id="dataTable" class="text-center table">
                        <thead class="bg-light text-capitalize">
                            <tr>
                                <th>No</th>
                                <th>NRM</th>
                                <th>Nama</th>
                                <th>Fakultas</th>
                                <th>Prodi</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($mahasiswa as $row)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $row->nrm }}</td>
                                    <td>{{ $row->nama }}</td>
                                    <td>{{ $row->fakultas }}</td>
                                    <td>{{ $row->prodi }}</td>
                                    <td>
                                        <form action="{{ route('mahasiswa.destroy', $row->id) }}" method="post">
                                            @csrf 
                                            @method('delete')
                                            <ul class="d-flex justify-content-center">
                                                <li class="mr-3"><a href="{{ route('mahasiswa.show', $row->id) }}" class="text-primary modal-btn" title="Lihat detail"><i class="fa fa-eye"></i></a> </li>
                                                <li class="mr-3"><a href="{{ route('mahasiswa.edit', $row->id) }}" class="text-secondary" title="Edit data"><i class="fa fa-edit"></i></a></li>
                                                <li><button type="submit" class="text-danger btn-submit" onclick="return confirm('Yakin akan hapus data?')" ><i class="fa fa-trash"></i></button></li>
                                            </ul>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')

<div id="theModal" class="modal fade text-center">
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>

<script>
    $('.modal-btn').on('click', function(e){
        e.preventDefault();
        $('#theModal').modal('show').find('.modal-content').load($(this).attr('href'));
    });
</script>
@endpush

resources/views/admin/mahasiswa/modal.blade.php
<div class="modal-header">
    <h5 class="modal-title">Detail Mahasiswa</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <div class="text-left">
        <h5 class="mb-3">
            {{ ucwords($mahasiswa->nama) }}
        </h5>

        <table class="table">
            <tr>
                <td>NRM</td>
                <td>:</td>
                <td>{{ $mahasiswa->nrm }}</td>
            </tr>
            <tr>
                <td>Fakultas</td>
                <td>:</td>
                <td>{{ $mahasiswa->fakultas }}</td>
            </tr>
            <tr>
                <td>Prodi</td>
                <td>:</td>
                <td>{{ $mahasiswa->prodi }}</td>
            </tr>
            <tr>
                <td>Angkatan</td>
                <td>:</td>
                <td>{{ $mahasiswa->angkatan }}</td>
            </tr>
          
            <tr>
                <td>Tanggal Lahir</td>
                <td>:</td>
                <td>{{ $mahasiswa->tanggal_lahir }}</td>
            </tr>
            <tr>
                <td>Jenis Kelamin</td>
                <td>:</td>
                <td>{{ ($mahasiswa->jenis_kelamin == 'l') ? 'Laki - Laki' : 'Perempuan' }}</td>
            </tr>
            <tr>
                <td>No. Telp</td>
                <td>:</td>
                <td>{{ $mahasiswa->no_telp }}</td>
            </tr>
            <tr>
                <td>Alamat</td>
                <td>:</td>
                <td>{{ $mahasiswa->alamat }}</td>
            </tr>               
        </table>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>